### ISSUE TITLE
Add restaurant association for scraped events

### ISSUE THREAD

**Issue by dlustre** [icssc/ZotMeal#169]
## Notes
- [x] ~~Current plan: do another scrape on brandywine page to get brandywine specific events and then filter the scraped events. Update schema to include restaurant~~
Scrape each individual link to also scrape each event's restaurant association

**Comment by bjsilva1** [comment]
Also, update database insert to use a primary key created by hashing the restaurant, date, and event name.

**Comment by dlustre** [comment]
Here's an edge case where campusdish doesn't even have a title for the event (absent in here and in the api thing). In the case of any of the information being missing, should we just not insert it to the database?

![image](https://github.com/icssc/ZotMeal/assets/83149801/de1f281e-01db-4146-b838-742705c8822c)
