### ISSUE TITLE
Update MenuPeriod table Schema and function

### ISSUE THREAD

**Issue by bjsilva1** [icssc/ZotMeal#206]
Change the MenuPeriod Schema to have it's primary key based on the restaurant, date, and meal period.
Also, change it to store the price in addition to the start and end times.

Refer to #205 for more information on what needs to be stored.

In addition, you should change the savePeriod function in `@zotmeal/api` menu services to reflect these changes to the schema.

**Comment by KatyH820** [comment]
no longer relevant after the recent schema update
